### ISSUE TITLE
Where to set permissions?

### ISSUE THREAD

**Issue by anxiousmodernman** [nubs/docker-npm-build#1]
In your documentation, you recommend setting permissions like so:

```
groupadd --gid 59944 npm-build
chmod -R g+w node_modules
chgrp -R npm-build node_modules
```

Should these be run on the host system or inside the docker container? I'm using OSX and `docker-machine`. I do realize that I do not have `groupadd` etc on OSX, so I am using the equivalent in Preferences.

**Comment by nubs** [comment]
It would be on the linux host (the machine that docker-machine creates).  I don't have much experience with running Docker on OSX, but assuming you also have the volume mounted from your OSX host to the docker machine, you may have to do something there so that ownership either is transferred or changed for your OSX host.

I am also working on changing the way this image works to have it run as root inside the container but recommending use of docker's [user namespace support](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-user-namespace-options) to map the root user to a different user outside of the container.  That will have potentially different requirements for a docker-machine setup on OSX.

**Comment by nubs** [comment]
If you do find out how to resolve this for OSX, feel free to leave some info and I'll update documentation.  Thanks for reporting this bug!

**Comment by nubs** [comment]
I opened up a PR for what I'm trying out at #2 - let me know whether that seems to be helpful or not.  Also, Docker just announced a beta of a Docker for Mac product that sounds like it could resolve a lot of these problems with volumes and such: https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by anxiousmodernman** [comment]
Thank you for being responsive. My problem here was with a fundamentally wrong approach to my problem.

_What didn't work:_ A docker build that tried to simultaneously mount my JS code AND do an actual `npm install .`. This gave me permissions issues and never seemed to work.

_What did work:_ A docker build that _only installed global tools_, like ruby, gulp (global), sass, etc. Then, the `CMD` portion of my build (only invoked at runtime) calls a script like `/usr/local/bin/start-dev-container.sh` which does some additional setup of config files (for private npm login) and runs the following in this order:

``` bash
npm install .
npm rebuild node-sass
exec gulp    # final command runs my gulp/browsersync dev server
```

**Comment by anxiousmodernman** [comment]
I also did end up creating a custom user. Full Dockerfile:

``` dockerfile
FROM node:onbuild

# Update + remove unnecessary packages.
RUN apt-get -y update --fix-missing && apt-get -y autoremove

# Install git and ruby.
RUN apt-get -y install git ruby vim

# Install Gulp globally.
RUN npm install -g gulp

# Install SASS
RUN gem install sass

# Create a play where files can be mounted.
RUN mkdir /code
WORKDIR /code/

# Add the startup script to a runnable location.
ADD start-dev-container.sh /usr/local/bin/start-dev-container.sh
RUN chmod +x /usr/local/bin/start-dev-container.sh

# Set up our non-root user.
RUN useradd builder
RUN mkdir /home/builder
RUN chown -R builder /home/builder
USER builder

CMD ["/usr/local/bin/start-dev-container.sh"]
```
